//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEDataBot.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BotsNew
    {
        public int Id { get; set; }
        public int NumberOfWindow { get; set; }
        public string HWND { get; set; }
        public string Family { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Channel { get; set; }
        public int ChangeVis { get; set; }
        public string Server { get; set; }
        public int TeleportForSale { get; set; }
    }
}
