//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoordinatesNew
    {
        public int Id { get; set; }
        public int Id_Bots { get; set; }
        public int NumberOfHeroes { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
    }
}
